### ISSUE TITLE
wrapper_class does not override mb-3

### ISSUE THREAD

**Issue by xi** [zostera/django-bootstrap5#101]
In django-bootstrap4, `bootstrap_field field form_group_class='foo'` will use a form group class of `foo`.

In django-bootstrap5, `bootstrap_field field wrapper_class='foo'` will use a wrapper class of `foo mb-3`.

This breaks cases where you need to remove the default margin.

A possible workaround is to use `layout='inline'`, but that adds unrelated styling which might cause other issues.

**Comment by dyve** [comment]
HI @xi, do you think the solution proposed in #113 is OK?

**Comment by xi** [comment]
I cannot test it right now but the code looks good.
