### ISSUE TITLE
RadioSelectButtonGroup doesn't render

### ISSUE THREAD

**Issue by dyve** [zostera/django-bootstrap5#111]
Our custom widget doesn't render because the `template_name` is overwritten in `renderers.py`.

**Comment by venomone** [comment]
Same issue here, very annoying. beside that nice project
![r_on](https://user-images.githubusercontent.com/43114687/120892604-7b472000-c60f-11eb-982f-3d38b232bf27.png)
![r_off](https://user-images.githubusercontent.com/43114687/120892605-7da97a00-c60f-11eb-9874-fa36057195be.png)

**Comment by gavinmh** [comment]
How can I work around this issue?
