### ISSUE TITLE
Support for Material Design Bootstrap (MDB)

### ISSUE THREAD

**Issue by mloepfe** [zostera/django-bootstrap5#159]
I just started using django_bootstrap5 in my projects where I'm using Material Design Bootstrap (MDB).
Unfortunately they use a different 'prefix' for (at least the event names). For example they use 'data-mdb-dismiss' instead of the 'data-bs-dismiss'. This has the effect, that for example the closing button on alerts does not work.

As the rendering of alerts is done in a function and not with a template, I have no chance to change it.
I don't know what the best solution for this problem is. But one could be to make this prefix ('mdb' or 'bs' or ..) configurable.

For sure there are be more places in the source code where MDB will have effects.

**Comment by dyve** [comment]
Thanks, I didn't know that. Worth investigating.

**Comment by dyve** [comment]
Returning to this issue, I'm not sure if we can follow up without becoming MDB experts. We'd need to know the exact differences between regular Bootstrap and MDB to guarantee this works. That won't happen.

What we might do, is add some settings to change the `data-bs` prefixes. This could be used to support Bootstrap variants. It does complicate the code, so another way we might go is to say "We support Vanilla Bootstrap only", and encourage people that need a variant to make a clone.

Input still welcome.

**Comment by dyve** [comment]
There hasn't been any interest in extending to support Material Design Bootstrap, so I'm clsoing the issues referencing this as Wontfix.
