### ISSUE TITLE
Please support form-outline layout variant

### ISSUE THREAD

**Issue by mloepfe** [zostera/django-bootstrap5#160]
I'm using Material Design Bootstrap (MDB) and there is very stylish form field layout variant in use. 
If you would allow layout='outline' and the use the 'form-outline' class instead of 'form-floating' it would work fine.

The problem is, that the label has to be rendered after the input widget (like as in floating layout). So there is no easy workaround for this.

<img width="577" alt="Bildschirmfoto 2021-08-05 um 10 55 11" src="https://user-images.githubusercontent.com/4748571/128322176-29e1abf8-183a-4979-a3d6-8ed2f6a3bea5.png">

<img width="565" alt="Bildschirmfoto 2021-08-05 um 10 55 41" src="https://user-images.githubusercontent.com/4748571/128322240-fae10227-b9c6-4920-8504-e61837b295b2.png">

**Comment by dyve** [comment]
See #159. The fact that MDB also (might) required changes in element order drives me towards "This needs a clone".

**Comment by dyve** [comment]
There hasn't been any interest in extending to support Material Design Bootstrap, so I'm clsoing the issues referencing this as Wontfix.
