### ISSUE TITLE
Permagutter on right side of page on typical wide monitor

### ISSUE THREAD

**Issue by enjoysmath** [zostera/django-bootstrap5#181]
![image](https://user-images.githubusercontent.com/1606391/135265194-193d0abd-aec3-46a9-b4e4-4be1a61f350c.png)

As  you can see the width of that container is 100%.  

I even tried putting `w-100` in the class field of the container divs.

I'm liking boostrap5 so far.  :)

**Comment by dyve** [comment]
This looks like an issue with Bootstrap 5, not with this specific package.  The best place to ask for help might be [StackOverflow](https://stackoverflow.com).
