### ISSUE TITLE
Form input group class mistake

### ISSUE THREAD

**Issue by Kanezal** [zostera/django-bootstrap5#306]
In `renders.py` there is a function called `make_input_group` that adds `addon_before_class` or `addon_after_class` .
But it creates a group form that looks like this:
```html
<div class="input-group">
	<div class="input-group-prepend">
		<span class="input-group-text">Some label</span>
	</div>
	<select name="some" class="form-select" title="" required="" id="id_some">
		<option value="" selected="">---------</option>
		<option value="1">Some option</option>
	</select>
</div>
```
So this html looks like this:
![image](https://user-images.githubusercontent.com/58330966/171924181-f9abd3cb-7f18-4a83-8b8d-730c35a22c83.png)
But in [Boostrap5 group form docs](https://getbootstrap.com/docs/5.0/forms/input-group/) there is nothing about class `input-group-prepend`. Because it was dropped:
![image](https://user-images.githubusercontent.com/58330966/171924341-a3efe56e-3299-45de-a0b5-bfe9b15eb401.png)

So html should look like this:
```html
<div class="input-group">
	<span class="input-group-text">Some label</span>
	<select name="some" class="form-select" title="" required="" id="id_some">
		<option value="" selected="">---------</option>
		<option value="1">Some option</option>
	</select>
</div>
```
And it should look like this:
![image](https://user-images.githubusercontent.com/58330966/171924064-419fdd9c-2b30-42af-86ee-b3b6f45efbb8.png)

I have pretty easy method to solve it by rewrite a `make_input_group` and a `make_input_group_addon` functions:
```py
def make_input_group_addon(self, content):
    if not content:
        return ""
    content = '<span class="input-group-text">{content}</span>'.format(content=content)
    return content

def make_input_group(self, html):
    if self.is_input_group:
        before = self.make_input_group_addon(self.addon_before)
        after = self.make_input_group_addon(self.addon_after)
        html = self.append_errors("{before}{html}{after}".format(before=before, html=html, after=after))
        html = '<div class="input-group">{html}</div>'.format(html=html)
    return html
```
Please add this in `django-bootstrap5`

**Comment by rteitge** [comment]
I can confirm this.

**Comment by blag** [comment]
Do you mind creating a PR for this?

**Comment by rteitge** [comment]
mea culpa. I recognized now that I used all the time the wrong package django-bootstrap-v5 ... thank you @blag for poking my nose on that mistake ... switched now and what a miracle! It works! This issue imho can be closed.
