### ISSUE TITLE
Merge with django-bootstrap-v5

### ISSUE THREAD

**Issue by nerdoc** [zostera/django-bootstrap5#314]
As there are 2 almost identical projects, both forked from [django-bootstrap4](https://github.com/zostera/django-bootstrap4), this only confuses users which is the "official" project.

I would strongly suggest you have a talk with @zelenij and merge these 2 projects (preferrably into zostera's [django-bootstrap5](https://github.com/zostera/django-bootstrap5)).

**Comment by maltoze** [comment]
the current library seems have many unimplemented options. such as `field_class` `addon_before_class` `addon_after_class`
