### ISSUE TITLE
Quickstart missing key instruction

### ISSUE THREAD

**Issue by turian** [zostera/django-bootstrap5#343]
```
"bootstrap5",
```

should be added to `INSTALLED_APPS` in `settings.py`.

This is not present in the docs :(

**Comment by jonatanskogsfors** [comment]
I just started using this the other day so take my comments with a grain of salt.

There is an instruction to add `"django_bootstrap5",` to INSTALLED_APPS. That should be enough, right?

**Comment by blag** [comment]
Yes, with the current distribution, it should be `django_bootstrap5`, and this is noted in both the README and the documentation.

@dyve This issue can be closed.
