### ISSUE TITLE
Is bootstrap5_extra_head working?

### ISSUE THREAD

**Issue by jonatanskogsfors** [zostera/django-bootstrap5#345]
I have a need to extend <head> in my project. I can't see anything about this in the documentation (perhaps it is basic Django knowledge?)

There is something called `bootstrap5_extra_head` in the source code. That sounds promising but I can't figure out how (or if) it is working.

I would be thankful if someone could give me some quick tips on what I could do.

**Comment by 0ge** [comment]
You can use the `bootstrap5_extra_head` block in your templates. It will show up in the `<head>` section of your HTML.

Example:
```html
{% extends 'django_bootstrap5/bootstrap5.html' %}

{% block bootstrap5_extra_head %}
<!-- TEST -->
{% endblock %}
{% block bootstrap5_title %}{% block title %}{% endblock %}{% endblock %}
```

renders as

```html
<!DOCTYPE html>
<html lang="en-us">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page title -->
    <title></title>
    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" rel="stylesheet">
    <!-- Bootstrap JavaScript if it is in head -->
<!-- TEST -->
</head>
<body>
<!-- Bootstrap JavaScript if it is in body -->
    <script crossorigin="anonymous" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
```

(I removed the empty lines)

I placed this in `base.html` (see the examples) to include, e.g., FontAwesome.

**Comment by jonatanskogsfors** [comment]
Thank you! Now I understand that the error I saw when trying this was unrelated.
