### ISSUE TITLE
rendering two input on the same line

### ISSUE THREAD

**Issue by MattiooFR** [zostera/django-bootstrap5#498]
How can I render two input or more on the same line ?

I don't want my form to be only be one input per each line.

**Comment by Actionb** [comment]
You could turn each field into a column of a row: wrap the fields you want on one line in a `div` with the `row` class, and then give each field wrapper the `col` class:
```html
  <div class="row mb-3">
  {% for field in fields %}
    {% bootstrap_field field wrapper_class="col" %}
  {% endfor %}
  </div>
```
Depending on the layout, you may want to specify a [horizontal gutter](https://getbootstrap.com/docs/5.3/layout/gutters/#horizontal-gutters) like this: `div class="row mb-3 gx-2` to tweak the spacing.

**Comment by dyve** [comment]
👍
