### ISSUE TITLE
i18n?

### ISSUE THREAD

**Issue by danielniccoli** [zostera/django-bootstrap5#527]
How do I handle translations in buttons? I'd like to migrate this to django-bootstrap5:

```django
<button class="btn btn-primary" type="submit">{% trans 'Change my password' %}</button>
```

**Comment by blag** [comment]
[Django's `i18n` documentation](https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#translate-template-tag) shows you how to translate a string into a template variable, and then you can use that in the example:

```html+django
{% translate 'Change my password' as submit_btn_content %}
{% bootstrap_button button_type="submit" content="{{ submit_btn_content }}" %}
```

**Comment by DREU007** [comment]
I've had the same thought, and based on my code the button looks like that `{{ button_name }}`

```html
{% translate 'Register' as button_name %}
{% bootstrap_button button_type="submit" content="{{ button_name }}" %}	

```

Any other suggestions?

**Comment by blag** [comment]
Try this:
```html+django
{% translate 'Register' as button_name %}
{% bootstrap_button button_type="submit" content=button_name %}	
```
