### ISSUE TITLE
Offline use?

### ISSUE THREAD

**Issue by holyda** [zostera/django-bootstrap5#532]
Hello! I didn't find any similar questions here. Could you clarify whether the library can be used offline? Can I install in static directory bootstrap5 and override links in settings.py? Thank you in advance!

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap5`, we'll be happy to reply over there!
