### ISSUE TITLE
Docs for template tags and filters gone?

### ISSUE THREAD

**Issue by christianwgd** [zostera/django-bootstrap5#543]
Hi, was missing the actual template tags and filters docs. They are listed but no content shows up. In older versions one could click on the topics and expand the contents.

![Bildschirmfoto 2024-01-05 um 14 33 07](https://github.com/zostera/django-bootstrap5/assets/9281647/2e3a6a36-b6d7-46e2-aad7-fe344a03c613)

Thanks for checking...

**Comment by christianwgd** [comment]
Tried to build the docs by myself and got some warnings:
```
No module named 'django_bootstrap5'
WARNING: autodoc: failed to import function 'templatetags.django_bootstrap5.bootstrap_formset_errors' from module 'django_bootstrap5'; the following exception was raised:
No module named 'django_bootstrap5'
```
for all templatetag docs

**Comment by suspiciousRaccoon** [comment]
Can confirm that the docs are still broken.

**Comment by marc-gist** [comment]
hopefully fixed soon, however, the base package docs can still be referenced, or the v5 option with is very similar to this. or the code :)

**Comment by dyve** [comment]
Looks like the problem is that the package is not installed before building the docs.

**Comment by dyve** [comment]
Might have to reopen this.

The changes to .readthedocs.yaml shouldhave fixed the build.
https://django-bootstrap5.readthedocs.io/en/feature-readthedocs/templatetags.html#bootstrap-form-errors

But the same build process does not yet fix it for the main branch.

**Comment by dyve** [comment]
Looks like the bug is solved, but due to caching some pages still do not show properly for me.  I will keep this open for a while to monitor, feel free to chime in.

**Comment by dyve** [comment]
Looks good to me now.
