### ISSUE TITLE
Jinja2 support

### ISSUE THREAD

**Issue by jorenham** [zostera/django-bootstrap5#548]
I'd like to see support for the Jinja2 template engine.

This should be easy to implement; Wagtail managed to do so in <100 lines, see [`wagtail/jinja2tags.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/jinja2tags.py) and its [documentation](https://docs.wagtail.org/en/stable/reference/jinja2.html).

**Comment by dyve** [comment]
Thanks for your suggestion. I'm not too familiar with Jinja2. If it's easy and you have an example, perhaps you can make a pull request?
