### ISSUE TITLE
Custom scss

### ISSUE THREAD

**Issue by DuncanTormey** [zostera/django-bootstrap5#566]
How do I import the scss variables? 
```
@import "../node_modules/bootstrap/scss/bootstrap";

.bg-yellow-100 {
    background-color: $yellow-100;
    color: #000;
}
```
doesn't seem to work.

**Comment by dyve** [comment]
It looks like you're trying to modify the Bootstrap CSS. That's outside the scope of this project.

For customized Bootstrap static files, please follow instructions at getbootstrap.com, and manually include your Bootstrap static files. The template tags and other utilities from this package will still work.
