### ISSUE TITLE
Difficulty cloning django-bootstrap5 using git protocol

### ISSUE THREAD

**Issue by forhadakhan** [zostera/django-bootstrap5#607]
I'm trying to clone the `zostera/django-bootstrap5` repository on GitHub. While the following command worked successfully:
```
git clone https://github.com/zostera/django-bootstrap5.git
```
This attempt using the `git` protocol failed:
```
git clone git://github.com/zostera/django-bootstrap5.git
```
The error message was: 
```
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Unknown error
```

### Expected Behavior:
Both `https` and `git` protocols should allow successful cloning of the repository.

### Possible Reasons:
- GitHub might be phasing out support for the `git` protocol, as it's less secure than `https`.
- Network firewalls could be blocking connections on port 9418 (commonly used for the `git` protocol).

### Request:
- If the `git` protocol is being deprecated, please consider adding a note to the repository's documentation or README file to inform users and recommend using `https` instead.

### My Setup/System
- OS: Windows 10 
- git version 2.43.0.windows.1
- Request made from PowerShell 
- `venv` was activated 
- Network firewall was active.

**Comment by dyve** [comment]
Access to GitHub is a GitHub issue, not a django-bootstrap5 issue.

**Comment by dyve** [comment]
![Scherm­afbeelding 2024-05-20 om 07 09 40](https://github.com/zostera/django-bootstrap5/assets/82315/5b66f9da-ed67-450b-82c6-7b8dc2c8d3ea)
