### ISSUE TITLE
Why would you use this package if you can directly include Bootstrap from a CDN or manually download it locally?

### ISSUE THREAD

**Issue by nbro** [zostera/django-bootstrap5#622]
It's unclear to me the advantages of using this package as opposed to the simpler alternatives of just including the links to a Bootstrap's CDN or even download the Bootstrap's source code manually into your static folder and include it in your templates as you would include any other static file.

So, why would you ever use this package? 

If the only advantage is that you can use Bootstrap in Django by downloading it via `pip`, then I fail to see how this is better than manually downloading the Bootstrap's source code or providing links to the CDN, which you can quickly do by going to the Bootstrap's web site. So, I assume there are other advantages.

**Comment by simonharris** [comment]
Would respectfully suggest the user spend 30 seconds reading the documentation and learning what this package does rather than raise bogus non-issues.

**Comment by nbro** [comment]
@simonharris I spent 30 seconds on the documentation and I did not find the purpose. The main page of the documentation has no description: https://django-bootstrap5.readthedocs.io/en/latest/index.html. The installation page has no description. The quick start page has no description. So, are we supposed to get a description of what this package is supposed to do by looking at the code? So, is that what you're saying? Why do you think I asked this question? Because I found a description of what this package does immediately?

**Comment by boxydog** [comment]
From https://github.com/zostera/django-bootstrap5:

"The goal of this project is to seamlessly blend Django and Bootstrap 5."

* Example Template
```
{% load django_bootstrap5 %}

<form action="/url/to/submit/" method="post" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="OK" %}
    {% bootstrap_button button_type="reset" content="Cancel" %}
</form>
```

Those are Django template tags that blend Django and bootstrap.

**Comment by dyve** [comment]
Thanks for your interest in the package @nbro. And thanks @simonharris and @boxydog for explaining.

Perhaps in the future there is room for a TL;DR type of introduction. For now, I hope the goal has been clarified. I know some people use this package as a shortcut to add the static Bootstrap files to their project, but the actual goal is in the template tags, including the form handling, and other utilities.
