### ISSUE TITLE
forms.ImageField adding `<br>` between the label and input fields.

### ISSUE THREAD

**Issue by PSNick** [zostera/django-bootstrap5#66]
Tested using Django 2.2 on Windows and Ubuntu 20.04

Using regular Django fields works just fine, but a bootstrap_field like `{% bootstrap_field form.image_upload show_label=False %}` introduces a `<br>` tag between the label and the input fields. It seems to happen both with the FileInput / ClearableFileInput widgets as far as I can tell.

![form](https://user-images.githubusercontent.com/8140506/115975666-f32d1f80-a566-11eb-849d-4957ae455089.PNG)

**Comment by dyve** [comment]
Thanks, will investigate.

**Comment by dyve** [comment]
I have added tests in #69. The `<br>` does not appear. Can you provide a failing test for this issue? Also, I notice attributes being inserted by Django-parsley. an you test without Django-parsley and see if the issue persists?

**Comment by PSNick** [comment]
Thank you for taking a look! It's a bit strange; I'll see if I can figure out what's causing it but I was sure it'd be django-bootstrap5 as it doesn't happen with regular django fields.
I also tried without parsley, but issue still persists.
![image](https://user-images.githubusercontent.com/8140506/116014518-f5aa7a80-a635-11eb-9a82-27004753ff72.png)

**Comment by dyve** [comment]
Without the `<br>`, the output also does not match what I see in the latest version. For example, the `title` tag without any content would not come from `django-bootstrap5`. If you can reproduce the issue in the latest version of this package, I'll be happy to take another look.
